# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: 
    url: /
    weight: 1
  - name: Home
    url: /#top
    weight: 2
  #- name: Model
  #  url: /model/  
  #  weight: 30
  - name: Publications
    url: publications/
    weight: 3
  - name: Get Access
    url: access/  
    weight: 4
 # - parent: Resources
 #   name: Blog
 #   url: blog/
